name: Random Posts CI/CD

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Make migrations
        run: |
          python random_posts/manage.py makemigrations --check --noinput
      - name: Apply Migrations
        run: |
          python random_posts/manage.py migrate

      - name: Collect the static files
        run: |
          python random_posts/manage.py collectstatic --noinput

      - name: Run Custom Commands
        run: |
          python random_posts/manage.py generate_fake_data

      - name: Run Unit Tests
        run: |
          python random_posts/manage.py test tests


